name: My Workflow
on:
    push:
        branches: [ main ]
jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
          - name: Get code
            uses: actions/checkout@v4

          - name: Set up python
            uses: actions/setup-python@v4
            with: 
                python-version: '3.11'

          - name: Install packages
            run: pip install -r requirements.txt

          - name: Run tests
            run: pytest -s -v

          - name: Success message
            run: echo "Tests completed successfully!"
